name: Insurance for Motorycles
favicon: null
layout_spectrum: 0.6345308169256896
typography_spectrum: 0.8406116219703108
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5829597404226661
  lightness: 0.4208394610323012
  saturation: 0.12439377815462649
  rhythmicContrast: 0.08939447556622326
purpose: []
